version: "3"
services:

  elasticsearch:
    image: elasticsearch:6.4.3
    container_name: elasticsearch
    ports:
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
