spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: "localhost:9300"
      cluster-name: "elasticsearch"

management:
  health:
    elasticsearch:
      enabled: false
  endpoints:
    web.base-path: "/"
    jmx.exposure.include: "*"
    health.show-details: "always"
